// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ldgbeajoyqwrqkirinmr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxkZ2JlYWpveXF3cnFraXJpbm1yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MTc1ODIsImV4cCI6MjA2OTI5MzU4Mn0.02gg8qtF508lw37YcS4vgcNWMLc0ukP66_GbAlIIm3g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});